#!/usr/bin/env python3
"""Back-sync MailChimp campaign content into the .md file.

When Tiff edits a draft campaign in MailChimp, those edits become the source
of truth. This script pulls the current MC body, converts it back to
markdown, and writes the .md file so the file mirrors MC.

Why:
  - Tweee's voice references (next-month prompts) read .md files via the
    diff-loop. If .md drifts from MC after Tiff edits, the prompts learn
    from Tweee's draft instead of Tiff's actual voice.
  - The fix in mailchimp_campaigns.py (commit c4b0cd8) makes the cron skip
    content updates on existing campaigns. This back-sync keeps the .md in
    sync the other direction.

Run modes:
  python3 newsletter_back_sync.py --month 2026-06 --audience lifestyle [--dry-run]
  python3 newsletter_back_sync.py --all  [--dry-run]    # sync every active draft

Cadence: cron every 15 min during active windows.
"""
from __future__ import annotations

import argparse
import difflib
import os
import re
import sys
from datetime import date, datetime
from pathlib import Path

import requests
from markdownify import markdownify

sys.path.insert(0, "/root/twy/paths")
from twy_paths import load_env  # noqa: E402

load_env()

sys.path.insert(0, str(Path(__file__).resolve().parent))
from newsletter import newsletter_path  # noqa: E402
from mailchimp_campaigns import _mc_auth, _mc_url  # noqa: E402
from twy_platform import locked_write  # noqa: E402


def _list_campaigns_cached(statuses: list[str]) -> list[dict]:
    """Fetch campaigns matching any of the given statuses. Cached per process.

    find_draft paginates 1000 campaigns per status and times out frequently
    when iterating many audiences. This bulk-fetches with minimal fields once
    so all audiences share a single API round-trip per status."""
    if not hasattr(_list_campaigns_cached, "_cache"):
        _list_campaigns_cached._cache = {}
    cache = _list_campaigns_cached._cache
    out: list[dict] = []
    for status in statuses:
        if status not in cache:
            r = requests.get(
                _mc_url("/campaigns"),
                auth=_mc_auth(),
                params={
                    "status": status,
                    "count": 1000,
                    "sort_field": "create_time",
                    "sort_dir": "DESC",
                    "fields": "campaigns.id,campaigns.web_id,campaigns.status,campaigns.send_time,campaigns.settings.title,campaigns.settings.subject_line",
                },
                timeout=60,
            )
            r.raise_for_status()
            cache[status] = r.json().get("campaigns", [])
        out.extend(cache[status])
    return out


def find_draft_local(title_contains: str, statuses: list[str]) -> dict | None:
    """Drop-in replacement for find_draft that uses the cached bulk fetch."""
    for c in _list_campaigns_cached(statuses):
        if title_contains in (c.get("settings", {}).get("title") or ""):
            return c
    return None

# audience key -> (md filename stem, campaign title template)
AUDIENCES = {
    "lifestyle":     ("lifestyle",     "{year}-{month:02d} — Lifestyle — Yoga Habit"),
    "non-lifestyle": ("non_lifestyle", "{year}-{month:02d} — Non-Lifestyle — Yoga Habit"),
    "ph1":           ("ph1",           "{year}-{month:02d} — PH1 — Yoga Habit"),
    "ph2":           ("ph2",           "{year}-{month:02d} — PH2 — Yoga Habit"),
    "reminder":      ("reminder",      "{year}-{month:02d} — Reminder — Yoga Habit"),
    "gentle_nudge":  ("gentle_nudge",  "{year}-{month:02d} — Gentle Nudge — Yoga Habit"),
    "non_opener":    ("non_opener",    "{year}-{month:02d} — Non-Opener — Yoga Habit"),
}

# Markers that bracket the editable body in the MC-rendered HTML.
MAIN_OPEN  = "<!-- MAIN CONTENT -->"
MAIN_CLOSE = "<!-- DIVIDER -->"

# CTA button HTML pattern. Generated by _CTA_LINK_RE in mailchimp_campaigns.
# Reverses any single trailing-paragraph markdown link.
CTA_BUTTON_RE = re.compile(
    r"<table[^>]*role=\"presentation\"[^>]*>"
    r".*?<a\s+href=\"(?P<href>[^\"]+)\"[^>]*>"
    r".*?<span[^>]*>(?P<text>[^<]+)</span>"
    r".*?</a>.*?</table>",
    re.DOTALL,
)


def _fetch_campaign_content(campaign_id: str) -> dict:
    r = requests.get(_mc_url(f"/campaigns/{campaign_id}/content"),
                     auth=_mc_auth(), timeout=15)
    r.raise_for_status()
    return r.json()


def _fetch_campaign_meta(campaign_id: str) -> dict:
    r = requests.get(_mc_url(f"/campaigns/{campaign_id}"),
                     auth=_mc_auth(), timeout=15)
    r.raise_for_status()
    return r.json()


def _extract_editable(html: str) -> str:
    """Return only the HTML inside the MAIN CONTENT ... DIVIDER markers."""
    i = html.find(MAIN_OPEN)
    if i == -1:
        raise ValueError(f"marker not found: {MAIN_OPEN!r}")
    j = html.find(MAIN_CLOSE, i)
    if j == -1:
        raise ValueError(f"marker not found: {MAIN_CLOSE!r}")
    return html[i + len(MAIN_OPEN):j]


def _normalize_cta_buttons(html: str) -> str:
    """Replace CTA <table>...<a>...<span>TEXT</span></a></table> with a plain
    paragraph containing a single <a>TEXT</a>. markdownify renders that as
    `[TEXT](URL)`."""
    return CTA_BUTTON_RE.sub(
        lambda m: f"<p><a href=\"{m.group('href')}\">{m.group('text').strip()}</a></p>",
        html,
    )


def _strip_outer_table_cell(html: str) -> str:
    """The editable region opens with <tr><td ...><div>...</div></td></tr>.
    Strip those wrappers so markdownify sees just the body."""
    # Drop opening <tr><td ...> through the first <div>.
    html = re.sub(r"^\s*<tr>\s*<td[^>]*>\s*<div>", "", html, count=1)
    html = re.sub(r"</div>\s*</td>\s*</tr>\s*$", "", html, count=1)
    return html


def html_to_md(html: str) -> str:
    """Strip wrappers + buttons, convert to markdown, normalize whitespace."""
    html = _normalize_cta_buttons(html)
    html = _strip_outer_table_cell(html)
    md = markdownify(
        html,
        heading_style="ATX",
        bullets="-",
        strip=["span"],   # keep <a>, <p>, <br>, etc.
    )
    # Markdownify emits trailing two-space soft breaks. The source .md
    # convention uses bare newlines + nl2br extension, which round-trips
    # identically via _md_to_html. Strip to match existing style and avoid
    # whitespace-only "edits".
    md = re.sub(r" +\n", "\n", md)
    # Collapse runs of >2 newlines.
    md = re.sub(r"\n{3,}", "\n\n", md)
    return md.strip() + "\n"


def reconstruct_md(subject_line: str, body_md: str) -> str:
    """Combine subject + body in the .md format (# Subject, blank, body)."""
    return f"# {subject_line}\n\n{body_md}".rstrip() + "\n"


def sync_audience(year: int, month: int, audience: str, *, dry_run: bool) -> dict:
    """Sync a single (year, month, audience). Returns a status dict."""
    if audience not in AUDIENCES:
        raise ValueError(f"unknown audience: {audience}")
    md_stem, title_tmpl = AUDIENCES[audience]
    campaign_title = title_tmpl.format(year=year, month=month)

    existing = find_draft_local(campaign_title, statuses=["save", "paused", "schedule"])
    if not existing:
        # Also check sent — if it's already sent, there's nothing to back-sync
        # (Tiff cannot edit a sent campaign anyway).
        sent = find_draft_local(campaign_title, statuses=["sent"])
        if sent:
            return {"audience": audience, "month": f"{year}-{month:02d}",
                    "status": "skipped", "reason": "already sent"}
        return {"audience": audience, "month": f"{year}-{month:02d}",
                "status": "skipped", "reason": "no draft in MC"}

    campaign_id = existing["id"]
    settings = existing.get("settings", {})
    subject_line = settings.get("subject_line") or settings.get("title", "")

    content = _fetch_campaign_content(campaign_id)
    body_html = _extract_editable(content.get("html", ""))
    body_md = html_to_md(body_html)
    new_md = reconstruct_md(subject_line, body_md)

    md_path = newsletter_path(year, month, md_stem)
    md_path.parent.mkdir(parents=True, exist_ok=True)
    current = md_path.read_text() if md_path.exists() else ""

    # Ignore trailing-whitespace-only differences (POSIX trailing newline,
    # historical files that don't end with one, etc.).
    if new_md.rstrip() == current.rstrip():
        return {"audience": audience, "month": f"{year}-{month:02d}",
                "status": "unchanged", "campaign_id": campaign_id}

    diff = "\n".join(difflib.unified_diff(
        current.splitlines(), new_md.splitlines(),
        fromfile=f"{md_path.name} (current)",
        tofile=f"{md_path.name} (MC)",
        lineterm="",
    ))

    if dry_run:
        return {"audience": audience, "month": f"{year}-{month:02d}",
                "status": "would-update", "campaign_id": campaign_id,
                "diff_lines": diff.count("\n") + 1,
                "diff_preview": diff[:1200]}

    # Write a sibling .bak so the prior content is recoverable.
    if md_path.exists():
        bak = md_path.with_suffix(md_path.suffix + f".bak.{datetime.now():%Y%m%dT%H%M%S}")
        bak.write_text(current)
    locked_write(md_path, new_md)
    return {"audience": audience, "month": f"{year}-{month:02d}",
            "status": "updated", "campaign_id": campaign_id,
            "diff_lines": diff.count("\n") + 1}


def parse_month(s: str) -> tuple[int, int]:
    y, m = s.split("-")
    return int(y), int(m)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--month", help="YYYY-MM (default: current MT month)")
    p.add_argument("--audience", choices=list(AUDIENCES), help="single audience")
    p.add_argument("--all", action="store_true",
                   help="sync every audience for the given month")
    p.add_argument("--dry-run", action="store_true",
                   help="print diffs without writing")
    args = p.parse_args()

    if args.month:
        year, month = parse_month(args.month)
    else:
        # Use current month in Mountain Time (matches run_campaigns convention).
        from zoneinfo import ZoneInfo
        now = datetime.now(ZoneInfo("America/Denver"))
        year, month = now.year, now.month

    targets = list(AUDIENCES) if args.all else [args.audience]
    if not args.all and not args.audience:
        p.error("--audience or --all required")

    import json
    results = [sync_audience(year, month, a, dry_run=args.dry_run) for a in targets]
    print(json.dumps(results, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
